# hyper-parameters
amp: true
bundle_root: null
ckpt_path: "$@bundle_root + '/model_fold' + str(@fold)"
data_file_base_dir: null
data_list_file_path: null
determ: false
fold: 0
input_channels: null
learning_rate: 0.025
num_images_per_batch: 2
num_epochs: 1250
num_patches_per_image: 1
num_sw_batch_size: 2
output_classes: null
overlap_ratio: 0.625
patch_size: null
patch_size_valid: null
softmax: true
resample: false

# training
loss:
  _target_: DiceCELoss2
  include_background: true
  sigmoid: $not @softmax
  smooth_dr: 1.0e-05
  smooth_nr: 0
  softmax: $@softmax
  squared_pred: true
  to_onehot_y: $@softmax
optimizer:
  _target_: torch.optim.AdamW
  lr: "@learning_rate"
  momentum: 0.9
  weight_decay: 1.0e-05
  params: "$@network.parameters()"
lr_scheduler:
  _target_: CosineAnnealingLRWithWarmup
  optimizer: "$@optimizer"
  warmup_epochs: 20
  warmup_multiplier: 0.1
  T_max: "@num_iterations"

# fine-tuning
finetune:
  activate: false
  pretrained_ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"

# validation
validate:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"
  save_mask: true
  ouptut_path: "$@bundle_root + '/prediction_fold' + str(@fold)"

# inference
infer:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"
  fast: false
  data_list_key: testing
  ouptut_path: "$@bundle_root + '/prediction_' + @infer#data_list_key"